<a href="https://colab.research.google.com/github/krishjoshi7/boilerplate-linear-regression-health-costs-calculator/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch fundamentals

In [215]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [216]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to Tensors

creating tensors

In [217]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [218]:
# A scalar has no dimenssion for this we use command (.ndim)
scalar.ndim

0

torch.tensor()  *always copies data

 *if you want to avoid copy use :- detach() or use requries_grad_()

In [219]:
# get tensor back as python int
scalar.item()

7

In [220]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [221]:
vector.ndim

1

In [222]:
vector.shape

torch.Size([2])

In [223]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [224]:
MATRIX.ndim

2

In [225]:
MATRIX[0]

tensor([7, 8])

In [226]:
MATRIX[1]

tensor([ 9, 10])

In [227]:
MATRIX.shape

torch.Size([2, 2])

In [228]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [229]:
TENSOR.ndim

3

In [230]:
TENSOR.shape

torch.Size([1, 3, 3])

In [231]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#NOTE

In Ml/DL for variable name

we will be using scalar, vector with lower case

MATRIX, TENSOR will use upper case

#Random Tensors

Why random tensors ?

Random tensors are importan  beacuse

The way many nueral network learns is that they start with tensors fullof random numbers and then adjust thoes random numbers to better represent the data

`start with random numbers -> look at data -> update random number -> look at data -> update random numbers`

In [232]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3786, 0.2582, 0.9646, 0.5609],
        [0.3442, 0.9770, 0.0862, 0.0633],
        [0.4598, 0.0424, 0.0914, 0.9365]])

In [233]:
random_tensor.ndim

2

In [234]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(224,224,3)) # height, width, colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [235]:
torch.rand(3,3)

tensor([[0.2864, 0.4549, 0.5208],
        [0.8938, 0.8779, 0.3574],
        [0.6307, 0.6580, 0.6022]])

# Zeros and Ones

In [236]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [237]:
#create a tenzors of all Ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [238]:
ones.dtype

torch.float32

In [239]:
random_tensor.dtype

torch.float32

# Creating a range of tensor and tensor-like

In [240]:
# use torch.range
torch.range(0, 10)

<ipython-input-240-0bc77e01e55b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#Note


torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use

torch.arange

In [241]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [242]:
#creating tensor like
# this function is used to create zeros tensor of the same shape aa assinged tensor to it
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# TENSOR DATATYPE

To see datatypes go to torch.tensor
             or


#Note
Tensor datatype is one of the 3 big error you'll run into with pytorch & deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device



In [243]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, # what datatype is the tennsor(e.g float32 or float16)
                               device=None, # what device is your tensor on
                                requires_grad=False) #whether or not to trace gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [244]:
float_32_tensor.dtype

torch.float32

In [245]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [246]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [247]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [248]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors (tensor attributes)


1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from tensor we can use `tensor.shape`
3. Tensor not on the right device - to get device(CPU/ GPU) from tensor we can use `tensor.device`

In [249]:
# create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)

tensor([[0.6925, 0.2841, 0.3302, 0.3379],
        [0.2384, 0.5405, 0.7805, 0.7742],
        [0.6585, 0.6603, 0.6430, 0.1857]])


In [250]:
# find out detail about some tensor
print(some_tensor)
print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.6925, 0.2841, 0.3302, 0.3379],
        [0.2384, 0.5405, 0.7805, 0.7742],
        [0.6585, 0.6603, 0.6430, 0.1857]])
datatype of tensor : torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on : cpu


# Manipulating Tensors (tensor operations)

Tensor operation includes :
 + Additions
 - Subtractions
 * multiplication (element-wise)
 * Division
 * Matrix multiplication




In [251]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [252]:
# Multiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [253]:
tensor

tensor([1, 2, 3])

In [254]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [255]:
# Try out python in built funtions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [256]:
torch.add(tensor, 10)

tensor([11, 12, 13])

#Matrix Multiplication

Two main ways of performing multiplication in nureal networks and deep learning


* Element-wise multiplication
* Matrix Multiplication(dot product)

There are two main rules that performing matrix multiplication needs to satisfy :

( 1 )  **INNER DIMENSIONS** must match:

* `(3, 2) @ (2,3)` this will work
* `(2, 3) @ (3'2)` This will work
* `(3, 2) @ (3,2)` This wont work


(2) The resulting matrix has the shape of ** Outer dimensions**:

* `(2,3) @ (3,2)` -> `(2, 2)`
* `(3,2) @ (2,3)` -> `(3, 3)`



In [257]:
#torch.matmul(torch.rand(3,2), torch.rand(3,2))

# most common error in ml

In [258]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4329, 1.0485, 1.0560],
        [0.3908, 0.9060, 0.9096],
        [0.4808, 0.6444, 0.6125]])

In [259]:
# Element wise multiplication
print (tensor, "*", tensor)
print(f"Equals : {tensor * tensor }")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [260]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [261]:
# Matrix multiplication by hand
(1*1) + (2*2) + (3*3)

14

In [262]:
tensor @ tensor

tensor(14)

In [263]:
%%time
value = 0
for i in range(len(tensor)) :
  value += tensor[i] * tensor[i]
value

CPU times: user 234 µs, sys: 0 ns, total: 234 µs
Wall time: 241 µs


tensor(14)

In [264]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 196 µs, total: 196 µs
Wall time: 518 µs


tensor(14)

#one of most common error in deep learning : shape error

In [265]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B =torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

In [266]:
tensor_A.shape

torch.Size([3, 2])

In [267]:
tensor_B.shape

torch.Size([3, 2])

In [268]:
#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(it's an alias for writing less code)

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

A **Transpose** switches the axis or dimensions of a given tensor

In [269]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [270]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [271]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [272]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Orignnal shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape} ")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension match")
print("Output:\n")
Output = torch.matmul(tensor_A, tensor_B.T)
print(Output)
print(f"\noutput shape : {Output.shape}")



Orignnal shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3]) 
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape : torch.Size([3, 3])


# Finding the min, max, mean, sum, etc(tensor aggregation)

In [273]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [274]:
x.dtype

torch.int64

In [275]:
#Find the min
torch.min(x)

tensor(1)

In [276]:
# Find the max
torch.max(x)

tensor(91)

In [277]:
# Find the mean
#torch.mean(x) this cannot run with long datatype we need to change it to other datatype
torch.mean(x.type(torch.float32))

tensor(46.)

#Note:
the `torch.mean()` function requires a tensor of flaot31 datatype to work


In [278]:
x.type(torch.float32).mean()

tensor(46.)

In [279]:

# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Finding the positional min and max

In [280]:
#Find the position in tensor that has the minimum vale with argmin() -> returns index position of target

#tensor where the minimum value occurs

x.argmin()

tensor(0)

In [281]:
x[0]

tensor(1)

In [282]:
# Find the position in tensor that has the maximum vale with argmax() -> returns index position of target

#tensor where the maximum value occurs

torch.argmax(x)

tensor(9)

In [283]:
x[9]

tensor(91)

#Reshaping, Stacking, squeezing and unsqueezing tensor

* Reshaping - reshape an input to a defined shape
* view - return an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensor on top of each other (vstack - vertical stack) or side by side (hstack - horizontal stack)
* squeeze- remove all `1` dimensions from a tensor
* unsqueeze - add a `1` dimension to a target tensor
* permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [284]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [285]:
# adda an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [286]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [287]:
#changing z changes x(because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [288]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [289]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [290]:
# torch.squeeze() - remove all single dimensions from a target tensor
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [291]:
x_reshaped.squeeze().shape

torch.Size([9])

In [292]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"perivous tensor :{x_reshaped}")
print(f"previous shape : {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f" new shape : {x_squeezed.shape}")

perivous tensor :tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape : torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
 new shape : torch.Size([9])


In [293]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f"previous target : {x_squeezed}")
print(f"previous shape : {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"new shape : {x_unsqueezed.shape}")

previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape : torch.Size([1, 9])


In [294]:
#torch.permute - rearrange3s the dimensions of a target
# this is mostly used in image type of probolem
x_original = torch.rand(size=(224, 224, 3)) #[height, width,colour_channels]

# permute the original tensor to rearange  the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 ->, 1->2, 2->0

print(f"previous shapes : {x_original.shape}")
print(f"new shape : {x_permuted.shape}") #[colour_channels, height, width]

previous shapes : torch.Size([224, 224, 3])
new shape : torch.Size([3, 224, 224])


#Indexing (selecting data from tensor)

* indexing with pytorch is similar to indexing with numpy

In [295]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [296]:
# Lets index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [297]:
# lets index on middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [298]:
# lets index on the most inner bracket (last dimension)
x[0,0,2]

tensor(3)

In [299]:
# task index 9
x[0,2,2]

tensor(9)

In [300]:
# you can also use ":" to select "all" of target dimension
x[:,0]

tensor([[1, 2, 3]])

In [301]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [302]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [303]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [304]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

# Pytorch tensors and NumPy

* Numpy is a popular scientific python numerical computing libarary
* And because of this, pytorch has functionality to interact with it.

* Data in numpy , want in pytorch tensor -> `torch.from_numpy(ndarray)`
* pytorch tensor to numpy `torch.Tensor.numpy()`

In [305]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor



(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [306]:
array.dtype

dtype('float64')

In [307]:
tensor.dtype

torch.float64

In [308]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [309]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [310]:
# tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [311]:
numpy_tensor.dtype

dtype('float32')

In [312]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility
(trying to take random out of random)

In short how a nueral network learns:

`starts with randoms numbers -> tensor operations -> update random numbers to try and maake them better representation of the data -> again -> again -> again...`

To reduce the randomness in nueral network and pytorch comes the concept of **random seed**  

Essentially what random seed does is "flavour" the randomness.

In [314]:
torch.rand(3,3)

tensor([[0.0971, 0.1471, 0.7833],
        [0.5636, 0.1463, 0.6964],
        [0.9650, 0.7762, 0.6681]])

In [315]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tennsor_B = torch.rand(3,4)

random_tensor_A, random_tennsor_B


(tensor([[0.4708, 0.8892, 0.1316, 0.2329],
         [0.8559, 0.9448, 0.2596, 0.7764],
         [0.6248, 0.8250, 0.1712, 0.6943]]),
 tensor([[0.8546, 0.8637, 0.6125, 0.5854],
         [0.1162, 0.4528, 0.4632, 0.6556],
         [0.2090, 0.7460, 0.8312, 0.4905]]))

In [316]:
print(random_tensor_A == random_tennsor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [318]:
# Lets make some random but reproducible tensor

import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
