<a href="https://colab.research.google.com/github/krishjoshi7/boilerplate-linear-regression-health-costs-calculator/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch fundamentals

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to Tensors

creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# A scalar has no dimenssion for this we use command (.ndim)
scalar.ndim

0

torch.tensor()  *always copies data

 *if you want to avoid copy use :- detach() or use requries_grad_()

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#NOTE

In Ml/DL for variable name

we will be using scalar, vector with lower case

MATRIX, TENSOR will use upper case

#Random Tensors

Why random tensors ?

Random tensors are importan  beacuse

The way many nueral network learns is that they start with tensors fullof random numbers and then adjust thoes random numbers to better represent the data

`start with random numbers -> look at data -> update random number -> look at data -> update random numbers`

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4141, 0.2735, 0.4537, 0.9006],
        [0.1211, 0.5064, 0.6464, 0.4301],
        [0.0853, 0.2139, 0.9554, 0.4773]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(224,224,3)) # height, width, colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
torch.rand(3,3)

tensor([[0.3059, 0.6915, 0.7153],
        [0.5589, 0.6791, 0.2280],
        [0.0475, 0.1719, 0.3311]])

# Zeros and Ones

In [22]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#create a tenzors of all Ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

# Creating a range of tensor and tensor-like

In [26]:
# use torch.range
torch.range(0, 10)

<ipython-input-26-0bc77e01e55b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#Note


torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use

torch.arange

In [27]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#creating tensor like
# this function is used to create zeros tensor of the same shape aa assinged tensor to it
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# TENSOR DATATYPE

To see datatypes go to torch.tensor
             or


#Note
Tensor datatype is one of the 3 big error you'll run into with pytorch & deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device



In [29]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, # what datatype is the tennsor(e.g float32 or float16)
                               device=None, # what device is your tensor on
                                requires_grad=False) #whether or not to trace gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors (tensor attributes)


1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from tensor we can use `tensor.shape`
3. Tensor not on the right device - to get device(CPU/ GPU) from tensor we can use `tensor.device`

In [35]:
# create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)

tensor([[0.7954, 0.5642, 0.2552, 0.0397],
        [0.4834, 0.9987, 0.4971, 0.8608],
        [0.6697, 0.6930, 0.1343, 0.8272]])


In [37]:
# find out detail about some tensor
print(some_tensor)
print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.7954, 0.5642, 0.2552, 0.0397],
        [0.4834, 0.9987, 0.4971, 0.8608],
        [0.6697, 0.6930, 0.1343, 0.8272]])
datatype of tensor : torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on : cpu


# Manipulating Tensors (tensor operations)

Tensor operation includes :
 + Additions
 - Subtractions
 * multiplication (element-wise)
 * Division
 * Matrix multiplication




In [38]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
tensor

tensor([1, 2, 3])

In [41]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# Try out python in built funtions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])